### ISSUE TITLE
Add state logos and sponsor logos

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/fantasy#2]
- [x] State logos
- [x] Sponsor logos

**Comment by Joe2k** [comment]
Are we gonna store the images in a cdn for faster delivery? and which one are we gonna use? I have previous exp with cloudinary and that gives a free tier and its good

**Comment by punchagan** [comment]
I don't mind using Cloudinary. Let's go with that! :)

**Comment by punchagan** [comment]
Added State logos in the Players List, which may be enough for now.
