### ISSUE TITLE
Issue with routing?

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/fantasy#3]
Navigating from https://fantasy.indiaultimate.org/ to https://fantasy.indiaultimate.org/players works. 
But directly navigating to https://fantasy.indiaultimate.org/players gives a 404.

**Comment by Joe2k** [comment]
Need to use HashRouter and set Homepage in package.json
Will do this in a bit

[Solution](https://stackoverflow.com/questions/71984401/react-router-not-working-with-github-pages)

**Comment by Joe2k** [comment]
Fixed

**Comment by punchagan** [comment]
Thanks for fixing this! 
Feel free to use [GitHub triggers](https://github.blog/2013-01-22-closing-issues-via-commit-messages/) to close issues.
