### ISSUE TITLE
Add link to code repository

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/fantasy#4]
In a footer? About page?

**Comment by Joe2k** [comment]
@punchagan  Added footer.. We can create a about page as well if needed. The footer is also bit distorted with github icon and text.. if there is a better way to do it we can edit it as well

[Footer Commit](https://github.com/india-ultimate/fantasy/commit/08c19069fb8199d6f76c96f455a7d58fd2b4d5fa)
